### ISSUE TITLE
rename to cplot?

### ISSUE THREAD

**Issue by nschloe** [endolith/complex_colormap#2]
This would coincide with similar functions; see, e.g., http://docs.sympy.org/0.6.7/modules/mpmath/basics.html. Also, the pypi entry is still available.

**Comment by endolith** [comment]
Well I intend to use similar colormaps for other things, too (where axes are time and frequency  rather than Re and Im), so I thought I'd focus the name on the colormap instead of the plot function.

**Comment by nschloe** [comment]
Fair enough.
